### ISSUE TITLE
bug in codevoorbeeld wiki

### ISSUE THREAD

**Issue by ghost** [pxlit-projects/battleship#2]
@wesleyhendrikx 

https://github.com/pxlit-projects/battleship/wiki/Client-Server-architectuur

Onderaan deze pagina (zie link) staat er een code voorbeeld (fetch) over hoe de token gebruikt moet worden:

'Authorization':'Bearer' + sessionStorage.getItem("token")

Deze code is echter verkeerd en levert een 401 authorization exception op. Dit komt omdat er geen spatie is achter het woord Bearer. (het feit dat er een spatie hoort is af te leiden uit de screenshot boven de code (zie link)).
De code zou er dus als volgt moeten uitzien:

'Authorization':'Bearer ' + sessionStorage.getItem("token")

Indien er nadien errors optreden met code 500, dan heeft dat te maken met de code in de backend die aangevuld moet worden door ons (leerlingen) zelf.

**Comment by custersnele** [comment]
Bedankt voor je opmerking! Ik heb het codevoorbeeld aangepast.
